version: '3.7'

services:

  worker:
    image: eassbhhtgu/telemetry-spike-1:latest
    ports:
    - 80:80/tcp
    - 443:443/tcp

  prometheus:
    image: prom/prometheus:latest
    depends_on:
    - worker
    ports:
    - 9090:9090/tcp
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
